// Generated by Wrangler by running `wrangler types`

interface Env {
	VISITOR_KV: KVNamespace;
	BRAND_ID: "southland";
	BIGQUERY_WEBHOOK_URL: "https://staging-webhook.example.com" | "https://production-webhook.example.com";
}
