//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  team: Team;
  teamConnection: TeamConnection;
  episodes: Episodes;
  episodesConnection: EpisodesConnection;
  guests: Guests;
  guestsConnection: GuestsConnection;
  topics: Topics;
  topicsConnection: TopicsConnection;
  shopCollections: ShopCollections;
  shopCollectionsConnection: ShopCollectionsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryEpisodesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEpisodesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EpisodesFilter>;
};


export type QueryGuestsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGuestsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuestsFilter>;
};


export type QueryTopicsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTopicsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicsFilter>;
};


export type QueryShopCollectionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShopCollectionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopCollectionsFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  team?: InputMaybe<TeamFilter>;
  episodes?: InputMaybe<EpisodesFilter>;
  guests?: InputMaybe<GuestsFilter>;
  topics?: InputMaybe<TopicsFilter>;
  shopCollections?: InputMaybe<ShopCollectionsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Team | Episodes | Guests | Topics | ShopCollections | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  publishDate: Scalars['String']['output'];
  updatedDate?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  author?: Maybe<Scalars['String']['output']>;
  reviewer?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  segment?: Maybe<Scalars['String']['output']>;
  targetKeyword?: Maybe<Scalars['String']['output']>;
  featuredImage?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  shopifyId?: Maybe<Scalars['Float']['output']>;
  shopifyHandle?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  updatedDate?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  reviewer?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  segment?: InputMaybe<StringFilter>;
  targetKeyword?: InputMaybe<StringFilter>;
  featuredImage?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  shopifyId?: InputMaybe<NumberFilter>;
  shopifyHandle?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type TeamLinks = {
  __typename?: 'TeamLinks';
  linkedin?: Maybe<Scalars['String']['output']>;
  twitter?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  youtube?: Maybe<Scalars['String']['output']>;
};

export type TeamPrimaryCta = {
  __typename?: 'TeamPrimaryCta';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Team = Node & Document & {
  __typename?: 'Team';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  bio: Scalars['String']['output'];
  photo?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  links?: Maybe<TeamLinks>;
  credentials?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  expertiseAreas?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  yearsExperience?: Maybe<Scalars['Float']['output']>;
  isAuthor?: Maybe<Scalars['Boolean']['output']>;
  isReviewer?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  active?: Maybe<Scalars['Boolean']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  hook?: Maybe<Scalars['String']['output']>;
  portraitBadge?: Maybe<Scalars['String']['output']>;
  credibilityStats?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  storySectionTitle?: Maybe<Scalars['String']['output']>;
  storyParagraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tieInHeading?: Maybe<Scalars['String']['output']>;
  tieInPoints?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  primaryCta?: Maybe<TeamPrimaryCta>;
  blogSectionTitle?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamLinksFilter = {
  linkedin?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  youtube?: InputMaybe<StringFilter>;
};

export type TeamPrimaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type TeamFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  photo?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  links?: InputMaybe<TeamLinksFilter>;
  credentials?: InputMaybe<StringFilter>;
  expertiseAreas?: InputMaybe<StringFilter>;
  yearsExperience?: InputMaybe<NumberFilter>;
  isAuthor?: InputMaybe<BooleanFilter>;
  isReviewer?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
  active?: InputMaybe<BooleanFilter>;
  subtitle?: InputMaybe<StringFilter>;
  hook?: InputMaybe<StringFilter>;
  portraitBadge?: InputMaybe<StringFilter>;
  credibilityStats?: InputMaybe<StringFilter>;
  storySectionTitle?: InputMaybe<StringFilter>;
  storyParagraphs?: InputMaybe<StringFilter>;
  tieInHeading?: InputMaybe<StringFilter>;
  tieInPoints?: InputMaybe<StringFilter>;
  primaryCta?: InputMaybe<TeamPrimaryCtaFilter>;
  blogSectionTitle?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Episodes = Node & Document & {
  __typename?: 'Episodes';
  title: Scalars['String']['output'];
  episodeNumber: Scalars['Float']['output'];
  season?: Maybe<Scalars['Float']['output']>;
  publishDate: Scalars['String']['output'];
  description: Scalars['String']['output'];
  longDescription?: Maybe<Scalars['String']['output']>;
  muxPlaybackId?: Maybe<Scalars['String']['output']>;
  audioUrl?: Maybe<Scalars['String']['output']>;
  youtubeUrl?: Maybe<Scalars['String']['output']>;
  applePodcastUrl?: Maybe<Scalars['String']['output']>;
  spotifyUrl?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  duration: Scalars['String']['output'];
  durationSeconds: Scalars['Float']['output'];
  topics?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EpisodesFilter = {
  title?: InputMaybe<StringFilter>;
  episodeNumber?: InputMaybe<NumberFilter>;
  season?: InputMaybe<NumberFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  longDescription?: InputMaybe<StringFilter>;
  muxPlaybackId?: InputMaybe<StringFilter>;
  audioUrl?: InputMaybe<StringFilter>;
  youtubeUrl?: InputMaybe<StringFilter>;
  applePodcastUrl?: InputMaybe<StringFilter>;
  spotifyUrl?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  durationSeconds?: InputMaybe<NumberFilter>;
  topics?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EpisodesConnectionEdges = {
  __typename?: 'EpisodesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Episodes>;
};

export type EpisodesConnection = Connection & {
  __typename?: 'EpisodesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EpisodesConnectionEdges>>>;
};

export type GuestsLinks = {
  __typename?: 'GuestsLinks';
  website?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  twitter?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
};

export type Guests = Node & Document & {
  __typename?: 'Guests';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  bio: Scalars['String']['output'];
  photo?: Maybe<Scalars['String']['output']>;
  links?: Maybe<GuestsLinks>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GuestsLinksFilter = {
  website?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
};

export type GuestsFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  photo?: InputMaybe<StringFilter>;
  links?: InputMaybe<GuestsLinksFilter>;
  featured?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type GuestsConnectionEdges = {
  __typename?: 'GuestsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Guests>;
};

export type GuestsConnection = Connection & {
  __typename?: 'GuestsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GuestsConnectionEdges>>>;
};

export type Topics = Node & Document & {
  __typename?: 'Topics';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  segment?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TopicsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  segment?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TopicsConnectionEdges = {
  __typename?: 'TopicsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Topics>;
};

export type TopicsConnection = Connection & {
  __typename?: 'TopicsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TopicsConnectionEdges>>>;
};

export type ShopCollectionsFaq = {
  __typename?: 'ShopCollectionsFaq';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type ShopCollections = Node & Document & {
  __typename?: 'ShopCollections';
  title: Scalars['String']['output'];
  handle: Scalars['String']['output'];
  persona?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  heroSubheadline?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  faq?: Maybe<Array<Maybe<ShopCollectionsFaq>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShopCollectionsFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type ShopCollectionsFilter = {
  title?: InputMaybe<StringFilter>;
  handle?: InputMaybe<StringFilter>;
  persona?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroSubheadline?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  faq?: InputMaybe<ShopCollectionsFaqFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ShopCollectionsConnectionEdges = {
  __typename?: 'ShopCollectionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ShopCollections>;
};

export type ShopCollectionsConnection = Connection & {
  __typename?: 'ShopCollectionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShopCollectionsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updateTeam: Team;
  createTeam: Team;
  updateEpisodes: Episodes;
  createEpisodes: Episodes;
  updateGuests: Guests;
  createGuests: Guests;
  updateTopics: Topics;
  createTopics: Topics;
  updateShopCollections: ShopCollections;
  createShopCollections: ShopCollections;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateEpisodesArgs = {
  relativePath: Scalars['String']['input'];
  params: EpisodesMutation;
};


export type MutationCreateEpisodesArgs = {
  relativePath: Scalars['String']['input'];
  params: EpisodesMutation;
};


export type MutationUpdateGuestsArgs = {
  relativePath: Scalars['String']['input'];
  params: GuestsMutation;
};


export type MutationCreateGuestsArgs = {
  relativePath: Scalars['String']['input'];
  params: GuestsMutation;
};


export type MutationUpdateTopicsArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicsMutation;
};


export type MutationCreateTopicsArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicsMutation;
};


export type MutationUpdateShopCollectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopCollectionsMutation;
};


export type MutationCreateShopCollectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: ShopCollectionsMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  team?: InputMaybe<TeamMutation>;
  episodes?: InputMaybe<EpisodesMutation>;
  guests?: InputMaybe<GuestsMutation>;
  topics?: InputMaybe<TopicsMutation>;
  shopCollections?: InputMaybe<ShopCollectionsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  team?: InputMaybe<TeamMutation>;
  episodes?: InputMaybe<EpisodesMutation>;
  guests?: InputMaybe<GuestsMutation>;
  topics?: InputMaybe<TopicsMutation>;
  shopCollections?: InputMaybe<ShopCollectionsMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  updatedDate?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  reviewer?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  segment?: InputMaybe<Scalars['String']['input']>;
  targetKeyword?: InputMaybe<Scalars['String']['input']>;
  featuredImage?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  shopifyId?: InputMaybe<Scalars['Float']['input']>;
  shopifyHandle?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TeamLinksMutation = {
  linkedin?: InputMaybe<Scalars['String']['input']>;
  twitter?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  youtube?: InputMaybe<Scalars['String']['input']>;
};

export type TeamPrimaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<TeamLinksMutation>;
  credentials?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  expertiseAreas?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  yearsExperience?: InputMaybe<Scalars['Float']['input']>;
  isAuthor?: InputMaybe<Scalars['Boolean']['input']>;
  isReviewer?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  hook?: InputMaybe<Scalars['String']['input']>;
  portraitBadge?: InputMaybe<Scalars['String']['input']>;
  credibilityStats?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  storySectionTitle?: InputMaybe<Scalars['String']['input']>;
  storyParagraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tieInHeading?: InputMaybe<Scalars['String']['input']>;
  tieInPoints?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  primaryCta?: InputMaybe<TeamPrimaryCtaMutation>;
  blogSectionTitle?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type EpisodesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  episodeNumber?: InputMaybe<Scalars['Float']['input']>;
  season?: InputMaybe<Scalars['Float']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  longDescription?: InputMaybe<Scalars['String']['input']>;
  muxPlaybackId?: InputMaybe<Scalars['String']['input']>;
  audioUrl?: InputMaybe<Scalars['String']['input']>;
  youtubeUrl?: InputMaybe<Scalars['String']['input']>;
  applePodcastUrl?: InputMaybe<Scalars['String']['input']>;
  spotifyUrl?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  durationSeconds?: InputMaybe<Scalars['Float']['input']>;
  topics?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GuestsLinksMutation = {
  website?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  twitter?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
};

export type GuestsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<GuestsLinksMutation>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TopicsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  segment?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ShopCollectionsFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type ShopCollectionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  handle?: InputMaybe<Scalars['String']['input']>;
  persona?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroSubheadline?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  faq?: InputMaybe<Array<InputMaybe<ShopCollectionsFaqMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, publishDate: string, updatedDate?: string | null, description: string, author?: string | null, reviewer?: string | null, tags?: Array<string | null> | null, segment?: string | null, targetKeyword?: string | null, featuredImage?: string | null, draft?: boolean | null, shopifyId?: number | null, shopifyHandle?: string | null, body?: any | null };

export type TeamPartsFragment = { __typename: 'Team', name: string, role: string, bio: string, photo?: string | null, email?: string | null, phone?: string | null, credentials?: Array<string | null> | null, expertiseAreas?: Array<string | null> | null, yearsExperience?: number | null, isAuthor?: boolean | null, isReviewer?: boolean | null, order?: number | null, featured?: boolean | null, active?: boolean | null, subtitle?: string | null, hook?: string | null, portraitBadge?: string | null, credibilityStats?: Array<string | null> | null, storySectionTitle?: string | null, storyParagraphs?: Array<string | null> | null, tieInHeading?: string | null, tieInPoints?: Array<string | null> | null, blogSectionTitle?: string | null, heroImage?: string | null, body?: any | null, links?: { __typename: 'TeamLinks', linkedin?: string | null, twitter?: string | null, website?: string | null, youtube?: string | null } | null, primaryCta?: { __typename: 'TeamPrimaryCta', label: string, url: string } | null };

export type EpisodesPartsFragment = { __typename: 'Episodes', title: string, episodeNumber: number, season?: number | null, publishDate: string, description: string, longDescription?: string | null, muxPlaybackId?: string | null, audioUrl?: string | null, youtubeUrl?: string | null, applePodcastUrl?: string | null, spotifyUrl?: string | null, thumbnail?: string | null, coverImage?: string | null, duration: string, durationSeconds: number, topics?: Array<string | null> | null, draft?: boolean | null, body?: any | null };

export type GuestsPartsFragment = { __typename: 'Guests', name: string, role?: string | null, company?: string | null, bio: string, photo?: string | null, featured?: boolean | null, body?: any | null, links?: { __typename: 'GuestsLinks', website?: string | null, linkedin?: string | null, twitter?: string | null, instagram?: string | null } | null };

export type TopicsPartsFragment = { __typename: 'Topics', name: string, description: string, icon?: string | null, segment?: string | null, body?: any | null };

export type ShopCollectionsPartsFragment = { __typename: 'ShopCollections', title: string, handle: string, persona?: string | null, seoDescription?: string | null, heroHeadline?: string | null, heroSubheadline?: string | null, heroImage?: string | null, body?: any | null, faq?: Array<{ __typename: 'ShopCollectionsFaq', question: string, answer: string } | null> | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, publishDate: string, updatedDate?: string | null, description: string, author?: string | null, reviewer?: string | null, tags?: Array<string | null> | null, segment?: string | null, targetKeyword?: string | null, featuredImage?: string | null, draft?: boolean | null, shopifyId?: number | null, shopifyHandle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, publishDate: string, updatedDate?: string | null, description: string, author?: string | null, reviewer?: string | null, tags?: Array<string | null> | null, segment?: string | null, targetKeyword?: string | null, featuredImage?: string | null, draft?: boolean | null, shopifyId?: number | null, shopifyHandle?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, name: string, role: string, bio: string, photo?: string | null, email?: string | null, phone?: string | null, credentials?: Array<string | null> | null, expertiseAreas?: Array<string | null> | null, yearsExperience?: number | null, isAuthor?: boolean | null, isReviewer?: boolean | null, order?: number | null, featured?: boolean | null, active?: boolean | null, subtitle?: string | null, hook?: string | null, portraitBadge?: string | null, credibilityStats?: Array<string | null> | null, storySectionTitle?: string | null, storyParagraphs?: Array<string | null> | null, tieInHeading?: string | null, tieInPoints?: Array<string | null> | null, blogSectionTitle?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: { __typename: 'TeamLinks', linkedin?: string | null, twitter?: string | null, website?: string | null, youtube?: string | null } | null, primaryCta?: { __typename: 'TeamPrimaryCta', label: string, url: string } | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, name: string, role: string, bio: string, photo?: string | null, email?: string | null, phone?: string | null, credentials?: Array<string | null> | null, expertiseAreas?: Array<string | null> | null, yearsExperience?: number | null, isAuthor?: boolean | null, isReviewer?: boolean | null, order?: number | null, featured?: boolean | null, active?: boolean | null, subtitle?: string | null, hook?: string | null, portraitBadge?: string | null, credibilityStats?: Array<string | null> | null, storySectionTitle?: string | null, storyParagraphs?: Array<string | null> | null, tieInHeading?: string | null, tieInPoints?: Array<string | null> | null, blogSectionTitle?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: { __typename: 'TeamLinks', linkedin?: string | null, twitter?: string | null, website?: string | null, youtube?: string | null } | null, primaryCta?: { __typename: 'TeamPrimaryCta', label: string, url: string } | null } | null } | null> | null } };

export type EpisodesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EpisodesQuery = { __typename?: 'Query', episodes: { __typename: 'Episodes', id: string, title: string, episodeNumber: number, season?: number | null, publishDate: string, description: string, longDescription?: string | null, muxPlaybackId?: string | null, audioUrl?: string | null, youtubeUrl?: string | null, applePodcastUrl?: string | null, spotifyUrl?: string | null, thumbnail?: string | null, coverImage?: string | null, duration: string, durationSeconds: number, topics?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EpisodesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EpisodesFilter>;
}>;


export type EpisodesConnectionQuery = { __typename?: 'Query', episodesConnection: { __typename?: 'EpisodesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EpisodesConnectionEdges', cursor: string, node?: { __typename: 'Episodes', id: string, title: string, episodeNumber: number, season?: number | null, publishDate: string, description: string, longDescription?: string | null, muxPlaybackId?: string | null, audioUrl?: string | null, youtubeUrl?: string | null, applePodcastUrl?: string | null, spotifyUrl?: string | null, thumbnail?: string | null, coverImage?: string | null, duration: string, durationSeconds: number, topics?: Array<string | null> | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GuestsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GuestsQuery = { __typename?: 'Query', guests: { __typename: 'Guests', id: string, name: string, role?: string | null, company?: string | null, bio: string, photo?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: { __typename: 'GuestsLinks', website?: string | null, linkedin?: string | null, twitter?: string | null, instagram?: string | null } | null } };

export type GuestsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GuestsFilter>;
}>;


export type GuestsConnectionQuery = { __typename?: 'Query', guestsConnection: { __typename?: 'GuestsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GuestsConnectionEdges', cursor: string, node?: { __typename: 'Guests', id: string, name: string, role?: string | null, company?: string | null, bio: string, photo?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: { __typename: 'GuestsLinks', website?: string | null, linkedin?: string | null, twitter?: string | null, instagram?: string | null } | null } | null } | null> | null } };

export type TopicsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TopicsQuery = { __typename?: 'Query', topics: { __typename: 'Topics', id: string, name: string, description: string, icon?: string | null, segment?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TopicsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicsFilter>;
}>;


export type TopicsConnectionQuery = { __typename?: 'Query', topicsConnection: { __typename?: 'TopicsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TopicsConnectionEdges', cursor: string, node?: { __typename: 'Topics', id: string, name: string, description: string, icon?: string | null, segment?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ShopCollectionsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ShopCollectionsQuery = { __typename?: 'Query', shopCollections: { __typename: 'ShopCollections', id: string, title: string, handle: string, persona?: string | null, seoDescription?: string | null, heroHeadline?: string | null, heroSubheadline?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faq?: Array<{ __typename: 'ShopCollectionsFaq', question: string, answer: string } | null> | null } };

export type ShopCollectionsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShopCollectionsFilter>;
}>;


export type ShopCollectionsConnectionQuery = { __typename?: 'Query', shopCollectionsConnection: { __typename?: 'ShopCollectionsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ShopCollectionsConnectionEdges', cursor: string, node?: { __typename: 'ShopCollections', id: string, title: string, handle: string, persona?: string | null, seoDescription?: string | null, heroHeadline?: string | null, heroSubheadline?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faq?: Array<{ __typename: 'ShopCollectionsFaq', question: string, answer: string } | null> | null } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  publishDate
  updatedDate
  description
  author
  reviewer
  tags
  segment
  targetKeyword
  featuredImage
  draft
  shopifyId
  shopifyHandle
  body
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  name
  role
  bio
  photo
  email
  phone
  links {
    __typename
    linkedin
    twitter
    website
    youtube
  }
  credentials
  expertiseAreas
  yearsExperience
  isAuthor
  isReviewer
  order
  featured
  active
  subtitle
  hook
  portraitBadge
  credibilityStats
  storySectionTitle
  storyParagraphs
  tieInHeading
  tieInPoints
  primaryCta {
    __typename
    label
    url
  }
  blogSectionTitle
  heroImage
  body
}
    `;
export const EpisodesPartsFragmentDoc = gql`
    fragment EpisodesParts on Episodes {
  __typename
  title
  episodeNumber
  season
  publishDate
  description
  longDescription
  muxPlaybackId
  audioUrl
  youtubeUrl
  applePodcastUrl
  spotifyUrl
  thumbnail
  coverImage
  duration
  durationSeconds
  topics
  draft
  body
}
    `;
export const GuestsPartsFragmentDoc = gql`
    fragment GuestsParts on Guests {
  __typename
  name
  role
  company
  bio
  photo
  links {
    __typename
    website
    linkedin
    twitter
    instagram
  }
  featured
  body
}
    `;
export const TopicsPartsFragmentDoc = gql`
    fragment TopicsParts on Topics {
  __typename
  name
  description
  icon
  segment
  body
}
    `;
export const ShopCollectionsPartsFragmentDoc = gql`
    fragment ShopCollectionsParts on ShopCollections {
  __typename
  title
  handle
  persona
  seoDescription
  heroHeadline
  heroSubheadline
  heroImage
  faq {
    __typename
    question
    answer
  }
  body
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const EpisodesDocument = gql`
    query episodes($relativePath: String!) {
  episodes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EpisodesParts
  }
}
    ${EpisodesPartsFragmentDoc}`;
export const EpisodesConnectionDocument = gql`
    query episodesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EpisodesFilter) {
  episodesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EpisodesParts
      }
    }
  }
}
    ${EpisodesPartsFragmentDoc}`;
export const GuestsDocument = gql`
    query guests($relativePath: String!) {
  guests(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GuestsParts
  }
}
    ${GuestsPartsFragmentDoc}`;
export const GuestsConnectionDocument = gql`
    query guestsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GuestsFilter) {
  guestsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GuestsParts
      }
    }
  }
}
    ${GuestsPartsFragmentDoc}`;
export const TopicsDocument = gql`
    query topics($relativePath: String!) {
  topics(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TopicsParts
  }
}
    ${TopicsPartsFragmentDoc}`;
export const TopicsConnectionDocument = gql`
    query topicsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TopicsFilter) {
  topicsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TopicsParts
      }
    }
  }
}
    ${TopicsPartsFragmentDoc}`;
export const ShopCollectionsDocument = gql`
    query shopCollections($relativePath: String!) {
  shopCollections(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShopCollectionsParts
  }
}
    ${ShopCollectionsPartsFragmentDoc}`;
export const ShopCollectionsConnectionDocument = gql`
    query shopCollectionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShopCollectionsFilter) {
  shopCollectionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShopCollectionsParts
      }
    }
  }
}
    ${ShopCollectionsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    episodes(variables: EpisodesQueryVariables, options?: C): Promise<{data: EpisodesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesQueryVariables, query: string}> {
        return requester<{data: EpisodesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesQueryVariables, query: string}, EpisodesQueryVariables>(EpisodesDocument, variables, options);
      },
    episodesConnection(variables?: EpisodesConnectionQueryVariables, options?: C): Promise<{data: EpisodesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesConnectionQueryVariables, query: string}> {
        return requester<{data: EpisodesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesConnectionQueryVariables, query: string}, EpisodesConnectionQueryVariables>(EpisodesConnectionDocument, variables, options);
      },
    guests(variables: GuestsQueryVariables, options?: C): Promise<{data: GuestsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuestsQueryVariables, query: string}> {
        return requester<{data: GuestsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuestsQueryVariables, query: string}, GuestsQueryVariables>(GuestsDocument, variables, options);
      },
    guestsConnection(variables?: GuestsConnectionQueryVariables, options?: C): Promise<{data: GuestsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuestsConnectionQueryVariables, query: string}> {
        return requester<{data: GuestsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GuestsConnectionQueryVariables, query: string}, GuestsConnectionQueryVariables>(GuestsConnectionDocument, variables, options);
      },
    topics(variables: TopicsQueryVariables, options?: C): Promise<{data: TopicsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicsQueryVariables, query: string}> {
        return requester<{data: TopicsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicsQueryVariables, query: string}, TopicsQueryVariables>(TopicsDocument, variables, options);
      },
    topicsConnection(variables?: TopicsConnectionQueryVariables, options?: C): Promise<{data: TopicsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicsConnectionQueryVariables, query: string}> {
        return requester<{data: TopicsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicsConnectionQueryVariables, query: string}, TopicsConnectionQueryVariables>(TopicsConnectionDocument, variables, options);
      },
    shopCollections(variables: ShopCollectionsQueryVariables, options?: C): Promise<{data: ShopCollectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopCollectionsQueryVariables, query: string}> {
        return requester<{data: ShopCollectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopCollectionsQueryVariables, query: string}, ShopCollectionsQueryVariables>(ShopCollectionsDocument, variables, options);
      },
    shopCollectionsConnection(variables?: ShopCollectionsConnectionQueryVariables, options?: C): Promise<{data: ShopCollectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopCollectionsConnectionQueryVariables, query: string}> {
        return requester<{data: ShopCollectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShopCollectionsConnectionQueryVariables, query: string}, ShopCollectionsConnectionQueryVariables>(ShopCollectionsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  